# Generated by Django 5.0.7 on 2024-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                default="M",
                max_length=1,
                null=True,
            ),
        ),
    ]
