# Generated by Django 5.0.7 on 2024-09-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parent", "0002_leave"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leave",
            old_name="parent_id",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="leave",
            old_name="student_id",
            new_name="student",
        ),
    ]
