# Generated by Django 5.0.7 on 2024-09-22 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parent", "0002_student_password_student_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.RemoveField(
            model_name="student",
            name="username",
        ),
    ]
