# Generated by Django 5.0.7 on 2024-09-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parent", "0004_student_password_student_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
