# Generated by Django 5.0.7 on 2024-09-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
