# Generated by Django 5.0.7 on 2024-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_timetable"),
    ]

    operations = [
        migrations.CreateModel(
            name="LunchMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Week",
                    models.CharField(
                        choices=[
                            ("week1", "week1"),
                            ("week2", "week2"),
                            ("week3", "week3"),
                            ("week4", "week4"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "Day",
                    models.CharField(
                        choices=[
                            ("monday", "monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                        ],
                        max_length=15,
                    ),
                ),
                ("Menu", models.CharField(max_length=250)),
            ],
        ),
    ]
