# Generated by Django 5.0.7 on 2024-09-18 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="student",
            name="section",
        ),
        migrations.AddField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="M", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
