# Generated by Django 5.0.7 on 2024-09-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
