# Generated by Django 5.0.7 on 2024-09-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parent", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "age", "class_id"),
                name="unique_student_entry",
            ),
        ),
    ]
