# Generated by Django 5.0.7 on 2024-09-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
