# Generated by Django 5.0.7 on 2024-09-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_class_remove_student_date_of_birth_student_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_id",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="student.class",
            ),
        ),
    ]
